# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jakub/NGT-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jakub/NGT-master/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakub/NGT-master/build/CMakeFiles /home/jakub/NGT-master/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakub/NGT-master/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ngtstatic

# Build rule for target.
ngtstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ngtstatic
.PHONY : ngtstatic

# fast build rule for target.
ngtstatic/fast:
	$(MAKE) -f lib/NGT/CMakeFiles/ngtstatic.dir/build.make lib/NGT/CMakeFiles/ngtstatic.dir/build
.PHONY : ngtstatic/fast

#=============================================================================
# Target rules for targets named ngt

# Build rule for target.
ngt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ngt
.PHONY : ngt

# fast build rule for target.
ngt/fast:
	$(MAKE) -f lib/NGT/CMakeFiles/ngt.dir/build.make lib/NGT/CMakeFiles/ngt.dir/build
.PHONY : ngt/fast

#=============================================================================
# Target rules for targets named versiondef

# Build rule for target.
versiondef: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 versiondef
.PHONY : versiondef

# fast build rule for target.
versiondef/fast:
	$(MAKE) -f lib/NGT/CMakeFiles/versiondef.dir/build.make lib/NGT/CMakeFiles/versiondef.dir/build
.PHONY : versiondef/fast

#=============================================================================
# Target rules for targets named ngt_exe

# Build rule for target.
ngt_exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ngt_exe
.PHONY : ngt_exe

# fast build rule for target.
ngt_exe/fast:
	$(MAKE) -f bin/ngt/CMakeFiles/ngt_exe.dir/build.make bin/ngt/CMakeFiles/ngt_exe.dir/build
.PHONY : ngt_exe/fast

#=============================================================================
# Target rules for targets named ngtq_exe

# Build rule for target.
ngtq_exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ngtq_exe
.PHONY : ngtq_exe

# fast build rule for target.
ngtq_exe/fast:
	$(MAKE) -f bin/ngtq/CMakeFiles/ngtq_exe.dir/build.make bin/ngtq/CMakeFiles/ngtq_exe.dir/build
.PHONY : ngtq_exe/fast

#=============================================================================
# Target rules for targets named hamming-uint8

# Build rule for target.
hamming-uint8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hamming-uint8
.PHONY : hamming-uint8

# fast build rule for target.
hamming-uint8/fast:
	$(MAKE) -f samples/hamming-uint8/CMakeFiles/hamming-uint8.dir/build.make samples/hamming-uint8/CMakeFiles/hamming-uint8.dir/build
.PHONY : hamming-uint8/fast

#=============================================================================
# Target rules for targets named l2-uint8

# Build rule for target.
l2-uint8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 l2-uint8
.PHONY : l2-uint8

# fast build rule for target.
l2-uint8/fast:
	$(MAKE) -f samples/l2-uint8/CMakeFiles/l2-uint8.dir/build.make samples/l2-uint8/CMakeFiles/l2-uint8.dir/build
.PHONY : l2-uint8/fast

#=============================================================================
# Target rules for targets named l2-uint8-range-search

# Build rule for target.
l2-uint8-range-search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 l2-uint8-range-search
.PHONY : l2-uint8-range-search

# fast build rule for target.
l2-uint8-range-search/fast:
	$(MAKE) -f samples/l2-uint8-range-search/CMakeFiles/l2-uint8-range-search.dir/build.make samples/l2-uint8-range-search/CMakeFiles/l2-uint8-range-search.dir/build
.PHONY : l2-uint8-range-search/fast

#=============================================================================
# Target rules for targets named cosine-float

# Build rule for target.
cosine-float: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cosine-float
.PHONY : cosine-float

# fast build rule for target.
cosine-float/fast:
	$(MAKE) -f samples/cosine-float/CMakeFiles/cosine-float.dir/build.make samples/cosine-float/CMakeFiles/cosine-float.dir/build
.PHONY : cosine-float/fast

#=============================================================================
# Target rules for targets named jaccard-sparse

# Build rule for target.
jaccard-sparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jaccard-sparse
.PHONY : jaccard-sparse

# fast build rule for target.
jaccard-sparse/fast:
	$(MAKE) -f samples/jaccard-sparse/CMakeFiles/jaccard-sparse.dir/build.make samples/jaccard-sparse/CMakeFiles/jaccard-sparse.dir/build
.PHONY : jaccard-sparse/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ngtstatic"
	@echo "... ngt"
	@echo "... versiondef"
	@echo "... ngt_exe"
	@echo "... ngtq_exe"
	@echo "... hamming-uint8"
	@echo "... l2-uint8"
	@echo "... l2-uint8-range-search"
	@echo "... cosine-float"
	@echo "... jaccard-sparse"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

